### PR TITLE
Fix filtering folder for Standalone generator

### PR DESCRIPTION
**Pull request by xpenatan**
This fix filtering folder.  It was impossible to use test case without maven/jar dependencies because it was allowing any folder to pass.

### CODE REVIEW

**Comment by fpetrola** [comment]
Why allowing any folder is breaking the build?

**Comment by xpenatan** [comment]
For example, dragome-bytecode-js-compiler is required to run the test.  Its allowing its classes to generate so even if I deny in the filter it goes in.  Same if I want import another project which should not be compiled to js. 


These folders will need to be allowed in TestsConfigurator 
eclipse\configuration\org.eclipse.osgi\215\0\.cp
eclipse\configuration\org.eclipse.osgi\214\0\.cp
\classes 
\test-classes

**Comment by fpetrola** [comment]
ok understood, so we should update DefaultDragomeConfigurator to include classes folder too?

**Comment by xpenatan** [comment]
Thats more complex question If we add to global configuration or just in TestConfiguration ^^.

For exemple: all my build setup use \bin and not \classes but lets talk about maven/eclipse proj which is set to \classes.

if '\classes' is from the current build project directory and not from imported project I think thats no problem, same if '\bin' is supported. 

When I ran with maven/eclipse These two folders was allowing:
eclipse\configuration\org.eclipse.osgi\215\0.cp
eclipse\configuration\org.eclipse.osgi\214\0.cp

But denying it it runs anyways so it was just creating more js size. 

'\test-classes' folder is specific for testing dragome so  adding to TestConfiguration may be a better option. 

I use this filterClassPath for my classical import/eclipse  setup:
```Java
	public boolean filterClassPath(String classpathEntry) {
		boolean include = super.filterClassPath(classpathEntry);
		include |= classpathEntry.contains("junit-");
		include |= classpathEntry.contains("hamcrest-");
		include |= classpathEntry.contains("dragome-js-commons\\bin");
		include |= classpathEntry.contains("dragome-w3c-standards\\bin");
		include |= classpathEntry.contains("dragome-core\\bin");
		include |= classpathEntry.contains("dragome-web\\bin");
		include |= classpathEntry.contains("dragome-js-jre\\bin");
		include |= classpathEntry.contains("dragome-js-jre\\target\\classes");
		include |= classpathEntry.contains("dragome-js-jre\\target\\test-classes");
		return include;
	}
```

**Comment by fpetrola** [comment]
I think DomHandlerApplicationConfigurator should add specific web folders and modules, while default configurator only includes core dependency. So in a standard web project this configuration will work alright  and could be extended for any particular case.

**Comment by xpenatan** [comment]
Updated commit with some failing tests   from #127   I added FIXME/TODO comments where its failing.

**Pull request merged**
