### PR TITLE
Classpath improvements

### PR DESCRIPTION
**Pull request by xpenatan**
Some improvements:

#075b808:
1 - Changed classpath filter to obey what is returned when launching with jetty. if its false dont allow classpath to generate.  Its the same issue as #126  where other "\classes" like from bytecode compiler was generating to js even if the filter was set to false.
2 - DefaultDragomeConfigurator now allow classes from "\classes" or "\bin" (Ex: If using dragome as imported project from eclipse).  Was allowing only for jar files. 
3 -  Added the ability to change the compiled javascript files path.  Returning null is the default which it first check for a "\classses" folder and rollback some folders and create a "compiled-js" folder (Same as before).  By returning dir path it will create "compiled-js" in that location. 
4 - fix test to allow "\test-classes" only. "\classes" is already allowed by DefaultDragomeConfigurator 

#2b49830:
1 - Eclipse Jetty plugins was throwing errors that compiler classes was not found. This resolve it. The main problem of this is that dragome-web project mix classes that will get generated and classes that its used to compile. 

#d857cbd
1 - Updated atmosphere dependency. Used 2 jetty plugins and both was causing errors and pointing to atmosphere.  The erros dint prevent from compiling/running though. Updating the dependency stopped the errors from throwing.

#cbec131
Disabled caching for tests.  Most of the time its not detecting changes to classes. For example I rolled back this commit to know why some flexjson classes was missing when launching the tests. The error was causing even after I rolled back. Then I realized that the problem is that the cache file was not updating.

### CODE REVIEW

**Comment by xpenatan** [comment]
#00aceb9
Improved compiling order.   
After sorting classpath It filter all classes and add them to a temp jar file (and resources). It wont add multiple class/packet so there wont be a issue with multiple entries exception.  Since classpath is already sorted what comes first stay and what is duplicate is ignored.

**Comment by xpenatan** [comment]
#6e1a591
Improved compiling order.   
After sorting classpath It filter all classes and add them to a temp jar file (and resources). It wont add multiple class/packet so there wont be a issue with multiple entries exception.  Since classpath is already sorted what comes first stay and what is duplicate is ignored.

**Comment by fpetrola** [comment]
I'm not able to compile the whole project, there is a class absent: com.dragome.web.html.dom.w3c.AbstractElement

**Comment by xpenatan** [comment]
huh? that class exist.  I rebuild everything and it works in eclipse and mvn clean install in cmd  

image

**Comment by fpetrola** [comment]
It's there: https://github.com/xpenatan/dragome-sdk/tree/classpathImprovements/dragome-web/src/main/java/com/dragome/web/html/dom/w3c
I dont know what happened with git, it's not present in the checkout I made in my computer, I'll add it again and commit

**Pull request closed without merging**
