### PR TITLE
Obfuscation ready

### PR DESCRIPTION
**Pull request by xpenatan**
#124 
The long waited obfuscation support is here

So what has changed. 

- It first call ClasspathFileFilter to filter classes that should compile.
These classes will be packed to a jar1 file.
Jar1 file will only contains classes that is set to compile.
If shrink is enable it will shrink and make a jar2 file.
If obfuscate is enable it will obfuscate and make a jar3 (with jar2 or jar1) file.
and then it will process the last jar file.

- added "getAdditionalObfuscateCodeKeepConfigFile" and "isObfuscateCode" method for obfuscation

- "getAdditionalCodeKeepConfigFile" and "getAdditionalObfuscateCodeKeepConfigFile" have now a Urls array in param so it can append multiple proguard configs. (usefull so a backend library can add some proguard configs and another project that use this backend append more).

Note:
DefaultClasspathFileFilter in BytecodeToJavascriptCompilerConfiguration  may not require it anymore because it already been filtered so I just added the DefaultClasspathFileFilter because there some reference deep inside the compiler.

Without proguard, libgdx test project javascript size is 12 MB.
With shrink and obfuscate is 3.93 MB.
Using yuicompressor goes down to 3.03 MB.
Total time is about 5-6 seconds.

All gdx backend project will use "-repackageclasses 'x'" config to reduce package name.

Using 2 pass for shrink and Obfuscate makes easier to edit the config file and It didn't work with a single pass because there was a issue with bcel.

### CODE REVIEW

**Comment by fpetrola** [comment]
Tests  are not passing with these  modifications, could it be something related to DragomeCompilerLauncher?

**Comment by xpenatan** [comment]
I'll check when I get home. gdx tests and shadertoy is working fine.

**Comment by xpenatan** [comment]
missing @Override made me miss to update the getAdditionalCodeKeepConfigFile method.

Obfuscation only work is some tests when getAdditionalObfuscateCodeKeepConfigFile is uncommented.

How to test it in a web browser so I can easily see the running js code?

**Comment by fpetrola** [comment]
you can use TestPage from examples java 8 project

**Comment by xpenatan** [comment]
@fpetrola  which classes does lambda stuff ? Need to keep them.

**Comment by fpetrola** [comment]
/dragome-js-jre/src/main/java/com/dragome/utils/DragomeCallsiteFactory.java

**Comment by xpenatan** [comment]
hi @fpetrola   instanceMethod from https://github.com/dragome/dragome-sdk/blob/master/dragome-js-jre/src/main/java/java/lang/reflect/Method.java#L134 is being null when obfuscation is used in lambda testes.   Which class create this "obj[sig]" ?

**Comment by nicolaichuk** [comment]
@xpenatan 

in this line

https://github.com/dragome/dragome-sdk/blob/master/dragome-js-jre/src/main/java/java/lang/reflect/Method.java#L130

```
ScriptHelper.put("obj", obj, this);
ScriptHelper.put("sig", this.signature, this);
```

**Comment by xpenatan** [comment]
@nicolaichuk  that is used to keep variables names after obfuscation.   the sig value may be wrong so that is why its getting null when testing lambda test.  I'll do more debugging when I get home.

**Comment by xpenatan** [comment]
Hi @fpetrola  I updated more stuff now and all reflectionTest works with obfuscation true except the new "testGetMethodNoParamCall" test which is failing.  Some lambda test is also failing that may be linked to this. 

for some reason Class#getDeclaredMethods is not finding "currentTimeMillis" method.

you can add "-keep class java.lang.System { *; }" to proguardObf to see the method better.

**Comment by xpenatan** [comment]
Hi @fpetrola  again.  All test except for "testCreatingBinaryOperatorWithLambda" now works with the signature fix

**Comment by fpetrola** [comment]
any idea about testCreatingBinaryOperatorWithLambda failing?

**Comment by xpenatan** [comment]
hi @fpetrola , the problem is that proguard is obfuscating apply method from java.util.function.BiFunction but is not changing it in lambdaTest class so it generates like this:
```Javascript
com_dragome_utils_DragomeCallsiteFactory.$create___java_lang_String__java_lang_String__java_lang_String__java_lang_String__java_lang_String__java_lang_Object__java_lang_String$java_lang_Object("com/dragome/tests/LambdaTests", "apply", "java.util.b.b", "()Ljava/util/b/b;", "com/dragome/tests/LambdaTests.lambda$8(Ljava/lang/Integer;Ljava/lang/Integer;)Ljava/lang/Integer; (6)", l20, "static");
```

I use "-keep class com.dragome.tests.* { *; }" for obfuscating (same as shrink).   

Does the keep above dont let proguard change methods that have been obfuscated and are called in "com.dragome.tests" package?


adding "-keep class java.util.function.BiFunction { *; }" to proguardObf.conf makes the test pass.

**Comment by xpenatan** [comment]
I dont know why proguard dint rename obfuscated method in test class so a fix is to keep all members in java.util.function package

**Pull request merged**
