### PR TITLE
Added missing method for Integer, Long class and small algorithm

### PR DESCRIPTION
**Pull request by xpenatan**
Added missing method for Integer, Long class (taken from gwt) and small algorithm for local_alias annotation to check for super interface/classes so the annotation is not needed to be added all the time in the current implemented method.  Its a small improvements for #66

### CODE REVIEW

**Comment by xpenatan** [comment]
okay. I dont see no problem with the current code. Just need a few fixes.

**Comment by fpetrola** [comment]
There are too issues I want to tackle using a standard annotation handling, one is about browsing super class annotations could be implemented outside compiler and the second is about manage local alias annotations in runtime too.

**Comment by xpenatan** [comment]
Why not make calling java from js by default ? could be tricky/break stuff ?  With it there is no need for annotations and no need to type all the classpath names to call a method.

**Comment by fpetrola** [comment]
You can call java from js using generated classes nomenclature, such as: 
var a = new com_badlogic_gdx_scenes_scene2d_utils_NinePatchDrawable();
a.$$init____com_badlogic_gdx_graphics_g2d_NinePatch$void(patch);

But the idea of local alias is about no coupling js call to this particular nomenclature that could be modified in a future and it's specific of dragome compiler.

**Comment by fpetrola** [comment]
And local alias is mostly for internal use, we should avoid its usage making some layer that solves the particular behavior we are implementing.

**Comment by xpenatan** [comment]
Okay.  Having to know the correct nomenclature is tricky ^^ and will break if you rename/move class to another place.  Anyways, good to know.

**Pull request merged**
