### PR TITLE
Remove JQuery dependency

### PR DESCRIPTION
**Pull request by bertung**
Remove JQuery dependency

### CODE REVIEW

**Comment by fpetrola** [comment]
There is a problem in generated code, I cannot start browser applications with these changes.

**Comment by bertung** [comment]
I will look into it. Is there a error message on the browser console?

**Comment by fpetrola** [comment]
It seems to be something related to jquery usage

**Comment by bertung** [comment]
Looks like console.js is pure Jquery. I have missed that. What is it for? All browsers have already equipped with a native console, is this really necessary?

**Comment by bertung** [comment]
Hmm looks like all commits I made are emitted to this PR. I Believe I made a mistake while creating this PR. I have removed your console implementation from the runtime.js and run.html. I have put the native console instead. I can commit them if you wish to this PR.

**Comment by fpetrola** [comment]
ok, is dragome-minimal-web-example running with these changes?

**Comment by bertung** [comment]
I would test the dragome-minimal-web-example but dragome-examples maven built is giving error messages, 

Failed to execute goal com.dragome:dragome-maven-plugin:0.96-beta3-SNAPSHOT:compileclient (default) on project dragome-todomvc: Execution default of goal com.dragome:dragome-maven-plugin:0.96-beta3-SNAPSHOT:compileclient failed: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory ->

http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by fpetrola** [comment]
I cannot reproduce this problem, but I found a bug in maven plugin, could you try using last repo version of dragome-sdk and dragome-examples?

**Comment by bertung** [comment]
dragome-sdk compiles just fine, but examples fails with the following exception on my end. I am not a maven expert but here is what I get;

[ERROR] Failed to execute goal com.dragome:dragome-maven-plugin:0.96-beta3-SNAPSHOT:compileclient (default) on project dragome-todomvc: Execution default of goal com.dragome:dragome-maven-plugin:0.96-beta3-SNAPSHOT:compileclient failed: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.dragome:dragome-maven-plugin:0.96-beta3-SNAPSHOT:compileclient (default) on project dragome-todomvc: Execution default of goal com.dragome:dragome-maven-plugin:0.96-beta3-SNAPSHOT:compileclient failed: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.dragome:dragome-maven-plugin:0.96-beta3-SNAPSHOT:compileclient failed: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at com.dragome.web.helpers.serverside.StandaloneDragomeAppGenerator.execute(StandaloneDragomeAppGenerator.java:207)
	at com.dragome.CompileClientMojo.execute(CompileClientMojo.java:27)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at com.dragome.compiler.DragomeJsCompiler.compile(DragomeJsCompiler.java:196)
	at com.dragome.web.helpers.serverside.DragomeCompilerLauncher.compileWithMainClass(DragomeCompilerLauncher.java:66)
	at com.dragome.web.helpers.serverside.StandaloneDragomeAppGenerator.compile(StandaloneDragomeAppGenerator.java:169)
	at com.dragome.web.helpers.serverside.StandaloneDragomeAppGenerator.execute(StandaloneDragomeAppGenerator.java:203)
	... 23 more
Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
	at com.dragome.compiler.utils.FileManager.getAllFilesInClasspath(FileManager.java:163)
	at com.dragome.compiler.DragomeJsCompiler.execute(DragomeJsCompiler.java:274)
	at com.dragome.compiler.DragomeJsCompiler.compile(DragomeJsCompiler.java:191)

**Comment by fpetrola** [comment]
Try using "maven clean install"
How are you executing maven?

**Comment by bertung** [comment]
I have used "maven clean install".

**Comment by bertung** [comment]
I did a maven clean test, now I get the following error.

Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/Users/bora/Documents/dragome-examples/examples-java7/src/main/java/com/dragome/examples/dom/TestDom1.java:[26,36] cannot find symbol
  symbol:   method setEventListener(org.w3c.dom.Element,<anonymous org.w3c.dom.events.EventListener>,java.lang.String,java.lang.String)
  location: class com.dragome.web.dispatcher.EventDispatcherImpl

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more

**Comment by fpetrola** [comment]
Sorry I was testing in "reference-method" branch. I've just fixed master branch too, pull the updates please.

**Comment by bertung** [comment]
Now it compiled. I will test my changes now.

**Comment by bertung** [comment]
Ok I think we hit the wall on JQuery. Are you using JQuery in any way in the produced javascript code?

**Comment by fpetrola** [comment]
There are some few usages (less than 10 I guess) mainly for onDocumentLoad events.

**Comment by bertung** [comment]
This line fails, what is the dollar sign for? a JQuery global?

$(function(){setupCheckCast(); _ed.executeMainClass();});

can we rewrite it like this?

(function(){setupCheckCast(); _ed.executeMainClass();})();

**Comment by intrigus** [comment]
`$(function(){setupCheckCast(); _ed.executeMainClass();});``

should be the same as
````javascript
$(document).ready(function(){
    setupCheckCast(); _ed.executeMainClass();}
});
````

The code inside the brackets is only called, when the document has been fully loaded, see https://api.jquery.com/ready/

**Comment by bertung** [comment]
Hmm I see, so we need to wait the document in a way. What is the minimum browser requirement for Dragome. We can pull a cross browser replacement of this JQuery dependency from there.

**Comment by bertung** [comment]
I put the following replacement which sounds like the intended use, application code starts the run but I get a non jquery related error.

   window.addEventListener("load", function(event) {
      setupCheckCast(); _ed.executeMainClass();
   });

the error:
Uncaught TypeError: Cannot read property 'classname' of undefined webapp.js:360 

the full stack trace:

dragomeJs.checkCast (webapp.js:360)
java_lang_String.prototype.$substring___int__int$java_lang_String() (webapp.js:63319)
java_lang_String.prototype.$startsWith___java_lang_String__int$boolean() (webapp.js:63265)
java_lang_String.prototype.$startsWith___java_lang_String$boolean() (webapp.js:63269)
java_lang_Class.$forName___java_lang_String$java_lang_Class() (webapp.js:59587)
java_lang_Class.$getType___java_lang_String$java_lang_Class() (webapp.js:59855)
java_lang_Boolean.$$clinit_() (webapp.js:57340)
flexjson_transformer_TransformerWrapper.prototype.$$init____flexjson_transformer_Transformer$void() (webapp.js:45092)
flexjson_TransformerUtil.$$clinit_() (webapp.js:52628)
flexjson_TransformerUtil.$getDefaultTypeTransformers$flexjson_transformer_TypeTransformerMap() (webapp.js:52784)
flexjson_JSONSerializer.prototype.$$init_$void() (webapp.js:49030)
com_dragome_services_serialization_FlexJsonSerializationService.prototype.$createSerializer$flexjson_JSONSerializer() (webapp.js:45182)
com_dragome_services_serialization_FlexJsonSerializationService.prototype.$$init_$void() (webapp.js:45166)
com_dragome_services_ServiceLocator.prototype.$$init_$void() (webapp.js:45502)
com_dragome_services_ServiceLocator.$getInstance$com_dragome_services_ServiceLocator() (webapp.js:45610)
com_dragome_services_WebServiceLocator.prototype.$$init_$void() (webapp.js:29785)
com_dragome_services_WebServiceLocator.$$clinit_() (webapp.js:29965)
com_dragome_services_WebServiceLocator.$getInstance$com_dragome_services_WebServiceLocator() (webapp.js:29972)
com_dragome_helpers_AnnotationsAdder.$addTypeAnnotation___java_lang_String__java_lang_String__java_lang_String__java_lang_String$void() (webapp.js:29726)
(anonymous function) (webapp.js:103038)

**Comment by bertung** [comment]
I am closing this PR, it is messed up. I will open individual files. It gets my whole tree.

**Comment by bertung** [comment]
https://github.com/dragome/dragome-sdk/pull/94

**Pull request closed without merging**
